---
# tasks file for demo-app
- name: Ensure webserver packages installed
  become: yes
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-virtualenv
    - python-pip
    - MySQL-python

- name: Ensure application source copied to host
  become: yes
  copy: 
    src: demo/app/
    dest: /var/www/demo
    mode: 0755
  notify: restart httpd

- name: Ensure virtual host config copied to host
  become: yes
  copy: 
    src: demo/demo.conf
    dest: /etc/httpd/conf.d/
    mode: 0755
  notify: restart httpd

- name: Ensure virtualenv is set up
  become: yes
  pip:
    requirements: /var/www/demo/requirements.txt
    virtualenv: /var/www/demo/.venv
  notify: restart httpd
  tags: 
    - pip

- name: Gather existing site configs
  find: 
    path: /etc/httpd/conf.d/
    excludes: demo.conf
  register: other_sites
  
- name: Remove other site configs
  file: 
    path: "{{ item }}"
    state: absent
  with_items: "{{ other_sites.files }}"
  notify: restart httpd