---
# tasks file for httpd
- name: Ensure webserver packages installed
  become: yes
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - mod_wsgi

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  become: yes
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  notify: restart httpd

- name: Ensure mod_wsgi enabled
  apache2_module:
    state: present
    name: wsgi
  notify: restart httpd

- name: Ensure Apache is started
  become: yes
  service:
    name: httpd
    enabled: yes
    state: started