---
- hosts: all
  gather_facts: no
  vars: 
    - hosts:
        - hostname: lb01
          ip: 104.196.175.167
        - hostname: db01
          ip: 35.196.144.238
        - hostname: app01
          ip: 35.231.78.175
        - hostname: app02
          ip: 34.73.210.224
  tasks: 
    - name: Configure hosts files
      become: yes
      lineinfile: 
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.hostname }}"
      with_items: "{{ hosts }}"
    
