---
- hosts: loadbalancers
  gather_facts: no
  tasks: 
    - name: Install nginx
      become: yes
      package: 
        state: present
        name: nginx
      tags: 
        - nginx
    - name: Ensure nginx is running
      become: yes
      service: 
        name: nginx
        enabled: yes
        state: started
      tags:
        - nginx
    - name: Configure nginx root file
      become: yes
      copy:
        dest: /etc/nginx/nginx.conf
        src: files/nginx.conf
    - name: Configure nginx site
      become: yes
      template: 
        src: templates/demo.conf.j2
        dest: /etc/nginx/conf.d/demo.conf
      notify: restart nginx
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
