---
- hosts: loadbalancers
  gather_facts: no
  tasks: 
    - name: Install nginx
      become: yes
      package: 
        state: present
        name: nginx
      tags: 
        - nginx
    - name: Ensure nginx is running
      become: yes
      service: 
        name: nginx
        enabled: yes
        state: started
      tags:
        - nginx
