---
- hosts: loadbalancers
  gather_facts: no
  become: yes
  tasks: 
    - name: Stop loadbalancer
      service: 
        state: stopped
        name: nginx
    - wait_for:
        port: 80
        state: drained

- hosts: webservers
  gather_facts: no
  become: yes
  tasks: 
    - name: Stop web server
      service:
        state: stopped
        name: httpd
    - wait_for:
        port: 80
        state: drained
- hosts: dbservers
  gather_facts: no
  become: yes
  tasks: 
    - name: Restart database
      service: 
        name: mariadb
        state: restarted
    - wait_for:
        port: 3306
        state: started

- hosts: loadbalancers
  gather_facts: no
  become: yes
  tasks:
    - name: Start loadbalancer
      service:
        state: started
        name: nginx
    - wait_for: 
        port: 80
        state: started

- hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: Start web server
      service:
        state: started
        name: httpd
    - wait_for: 
        port: 80
        state: started
  
